services:
  shader-dsp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-UTC}
    volumes:
      - .:/workspace
      - shader-dsp-history:/commandhistory
      - shader-dsp-config:/home/developer/.claude
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Share X11 socket for GUI (Linux/macOS)
      # ALSA devices - only mount if they exist (Linux)
      - ${ALSA_DEVICES:-/dev/null}:/dev/snd:rw
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
      - CLAUDE_CONFIG_DIR=/home/developer/.claude
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - XDG_RUNTIME_DIR=/tmp/runtime-developer
      - XDG_DATA_HOME=/tmp/data
      - XDG_CONFIG_HOME=/tmp/config
      - XDG_CACHE_HOME=/tmp/cache
      - RASPBERRY_PI_SIMULATION=true
      - PI_ARCH=arm64
      - PI_MODEL=5
      - LD_LIBRARY_PATH=/opt/vc/lib
      - PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig
      - QT_X11_NO_MITSHM=1
      - _X11_NO_MITSHM=1
      - _MITSHM=0
      # Audio driver will be set by entrypoint script based on OS
      - SDL_AUDIODRIVER=dummy
      - SDL_VIDEODRIVER=${SDL_VIDEODRIVER:-x11}
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=3.3
      - MESA_GLSL_VERSION_OVERRIDE=330
    working_dir: /workspace
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN  # Add SYS_ADMIN for device access
      - SYS_PTRACE # For debugging
    # Conditional device mapping - only for Linux with ALSA
    devices:
      - ${ALSA_DEVICES:-/dev/null}:/dev/snd:rw
    # Remove host network mode for better cross-platform compatibility
    ports:
      - "8080:8080"  # Optional: expose a port if needed
    tty: true
    stdin_open: true
    command: /bin/bash
    # Set the user to match the UID:GID in Dockerfile (2000:2000)
    user: "2000:2000"
    # Raspberry Pi 5 simulation constraints
    deploy:
      resources:
        limits:
          cpus: '4.0'  # Pi 5 has 4 cores
          memory: 8G   # Pi 5 has 4GB/8GB RAM
        reservations:
          cpus: '2.0'
          memory: 2G

volumes:
  shader-dsp-history:
  shader-dsp-config: