services:
  shader-dsp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-UTC}
    volumes:
      - .:/workspace
      - shader-dsp-history:/commandhistory
      - shader-dsp-config:/home/developer/.claude
      - ${HOME}/.cursor_server:/host_cursor_server:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Share X11 socket for GUI (Linux/macOS)
      # ALSA devices - only mount if they exist (Linux)
      - ${ALSA_DEVICES:-/dev/null}:/dev/snd:rw
      # PulseAudio configuration and cookie (macOS)
      - ./conf/pulse-client.conf:/root/.config/pulse/client.conf:ro
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie:rw
    environment:
      # Timezone
      - TZ=${TZ:-UTC}
      
      # Raspberry Pi 5 simulation environment
      - RASPBERRY_PI_SIMULATION=true
      - PI_ARCH=arm64
      - PI_MODEL=5
      
      # Development container
      - DEVCONTAINER=true
      
      # Node.js and Claude configuration
      - NODE_OPTIONS=--max-old-space-size=2048
      - NPM_CONFIG_PREFIX=/usr/local/share/npm-global
      - CLAUDE_CONFIG_DIR=/home/developer/.claude
      
      # PATH configuration
      - PATH=/usr/local/share/npm-global/bin:/workspace/build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      
      # Display and X11 configuration - Optimized for performance
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - SDL_VIDEODRIVER=${SDL_VIDEODRIVER:-x11}
      - QT_X11_NO_MITSHM=1
      - _X11_NO_MITSHM=1
      - _MITSHM=0
      
      # XDG environment variables
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - XDG_DATA_HOME=/tmp/data
      - XDG_CONFIG_HOME=/tmp/config
      - XDG_CACHE_HOME=/tmp/cache
      
      # OpenGL and Mesa configuration - Optimized for performance
      - LIBGL_ALWAYS_SOFTWARE=0  # Changed to 0 to use hardware acceleration when available
      - MESA_GL_VERSION_OVERRIDE=3.3
      - MESA_GLSL_VERSION_OVERRIDE=330
      - MESA_GLTHREAD=1  # Enable Mesa threading
      - MESA_DEBUG=0     # Disable Mesa debug output for performance
      
      # Performance optimizations
      - SDL_VIDEO_X11_NODIRECTCOLOR=1
      - SDL_VIDEO_X11_XRANDR=1
      - SDL_VIDEO_X11_XVIDMODE=1
      - SDL_VIDEO_X11_XINERAMA=1
      - SDL_VIDEO_X11_XDBE=1
      - SDL_VIDEO_X11_DGAMOUSE=0  # Disable DGA mouse for better compatibility
      
      # Threading optimizations
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - OPENBLAS_NUM_THREADS=4
      
      # Raspberry Pi library paths
      - LD_LIBRARY_PATH=/opt/vc/lib
      - PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig
      
      # Audio configuration
      - SDL_AUDIODRIVER=pulse
      - PULSE_SERVER=host.docker.internal
      - PULSE_COOKIE=/root/.config/pulse/cookie
      
      # Shell configuration
      - SHELL=/bin/bash
    working_dir: /workspace
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN  # Add SYS_ADMIN for device access
      - SYS_PTRACE # For debugging
      - SYS_NICE   # Add SYS_NICE for priority control
    # Conditional device mapping - only for Linux with ALSA
    devices:
      - ${ALSA_DEVICES:-/dev/null}:/dev/snd:rw
    # Remove host network mode for better cross-platform compatibility
    ports:
      - "8080:8080"  # Optional: expose a port if needed
    tty: true
    stdin_open: true
    command: bash -lc "/usr/local/bin/link_cursor_server.sh; exec bash"
    # Set the user to root for full access
    user: "root"
    # Performance-optimized resource constraints
    deploy:
      resources:
        limits:
          cpus: '4.0'  # Pi 5 has 4 cores
          memory: 8G   # Pi 5 has 4GB/8GB RAM
        reservations:
          cpus: '2.0'
          memory: 2G
    # Add performance optimizations
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    # Add real-time scheduling group
    group_add:
      - video
    # Add security options for better performance
    security_opt:
      - seccomp:unconfined
    # Add tmpfs for better I/O performance
    tmpfs:
      - /tmp:size=1G,noexec,nosuid,nodev
      - /var/tmp:size=1G,noexec,nosuid,nodev

volumes:
  shader-dsp-history:
  shader-dsp-config: